switch from oslosphinx to openstackdocstheme
Changed upstream in https://review.openstack.org/477660

Use autosetup -S git to create fake git repo in order to avoid error
when building docs:
...
fatal: Not a git repository (or any of the parent directories): .git
Exception occurred:
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit

Change-Id: Ic3e89711753470da16a077af306c28d7bc9c0079